{
  "impact": "major",
  "name": "Connectivity issues",
  "updates": [
    {
      "date": "2021-09-17T05:52:54.378Z",
      "status": "investigating",
      "content": "We are experiencing some connectivity issues at the moment.\n\nInvestigation is in progress."
    },
    {
      "date": "2021-09-17T06:09:54.211Z",
      "status": "investigating",
      "content": "Heroku is investigating an issue on their platform ( https://status.heroku.com/incidents/2359 )"
    },
    {
      "date": "2021-09-17T07:04:42.367Z",
      "status": "investigating",
      "content": "We are applying a mitigation strategy in the meantime"
    },
    {
      "date": "2021-09-17T07:20:31.775Z",
      "content": "We have created a new application and changed DNS entries to circumvent Heroku's issues, and it seems to be working: requests are coming to our application again. We're monitoring the situation of course, but things should be back to normal.",
      "status": "monitoring"
    },
    {
      "date": "2021-09-17T08:11:21.617Z",
      "content": "Heroku is solving the root issue. We're waiting until the incident is fully resolved on their end to switch back to our original application.",
      "status": "monitoring"
    },
    {
      "date": "2021-09-17T09:00:50.441Z",
      "status": "monitoring",
      "content": "Heroku fixed the problem.\n\nWe are going to route the requests to our old app again. Some downtime is expected during the process."
    }
  ]
}